@startuml project flow
partition "1. Datengewinnung" {
    :Lese SQL-Dateien aus  Verzeichnis (defineren checks);
    :Führe Abfragen gegen **Versio.io Datenbank** aus;
}

partition "2. Aufbereitung" {
    :Normalisiere Daten;
}

partition "3. Integration" {
    :Sende Daten via **REST API** an Versio.io;
}

partition "4. Ergebnis in Versio.io" {
    if (Verstoß liegt vor?) then (ja)
        :Erzeuge **Violation**;
        :Q.A wird benachrichtigt;
        stop
    else (nein)

        stop
    endif
}
@enduml